export const WAITING_FOR_OFFERS = 'WAITING_FOR_OFFERS';
export const WAITING_FOR_HELPER_START = 'WAITING_FOR_HELPER_START';
export const WAITING_FOR_CLIENT_APPROVAL = 'WAITING_FOR_CLIENT_APPROVAL';
export const WAITING_FOR_FINISH_REQUEST = 'WAITING_FOR_FINISH_REQUEST';
export const WAITING_FOR_CLIENT_PAYMENT = 'WAITING_FOR_CLIENT_PAYMENT';
