export const WAITING_FOR_OFFER_RESPONSE = 'WAITING_FOR_OFFER_RESPONSE';
export const WAITING_FOR_HELPER_START = 'WAITING_FOR_HELPER_START';
export const WAITING_FOR_CLIENT_START = 'WAITING_FOR_CLIENT_START';
export const WAITING_FOR_FINISH_REQUEST = 'WAITING_FOR_FINISH_REQUEST';
export const WAITING_FOR_ADMIN_APPROVAL = 'WAITING_FOR_ADMIN_APPROVAL';
